site_name: ESTRUCTURATOR
nav:
- Introduccion: index.md
- El entorno: entorno.md
- El lenguaje: lenguaje.md
- Estructura de datos: estructura-de-datos.md
theme: 'material'
docs_dir: 'markdown_files'

#Highlight ED1
extra_css: ['assets/ed1.css']
extra_javascript: ['https://cdnjs.cloudflare.com/ajax/libs/ace/1.3.3/ace.js','https://cdnjs.cloudflare.com/ajax/libs/ace/1.3.3/ext-static_highlight.js','assets/ed1.js']


# Options Material Theme
extra:
  version: '0.1.0'
  palette:
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Anterior'
    next: 'Siguiente'
    search: 'Buscar'
